version: "3.8"

services:
  server-api:
    build:
      context: ./server-api          # 👈 this folder contains package.json
      dockerfile: ../Dockerfile.node # 👈 use the shared Dockerfile
    container_name: mosque-server-api
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: production
      PORT: 5001
      DOMAIN: http://localhost
    volumes:
      - ./server-api/data:/data
    env_file:
      - ./server-api/.env

  mosque-website:
    build:
      context: ./mosque-website      # 👈 this folder contains package.json
      dockerfile: ../Dockerfile.node
    container_name: mosque-website
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: production
      PORT: 5173
      DOMAIN: http://localhost
    volumes:
      - ./mosque-website/data:/data
    env_file:
      - ./mosque-website/.env
