version: "3.8"

services:
  mosque-website:
    build: ./
    container_name: mosque-website
    restart: unless-stopped
    ports:
      - "4173:4173"
    environment:
      NODE_ENV: production
      PORT: 4173
      DOMAIN: http://localhost
    volumes:
      - ./data:/data     # host folder : /data in container
    env_file:
      - ./.env
